// =============================================================================
// ROAM — Safety, Health & Visa Data (local only, no network)
// For prep screen Overview, Health, and Visa tabs
// =============================================================================

export type AdvisoryLevel = 1 | 2 | 3 | 4;
export type AdvisoryLabel =
  | 'Safe'
  | 'Exercise Caution'
  | 'Avoid Non-Essential Travel'
  | 'Do Not Travel';

export interface SafetyData {
  country: string;
  destinations: string[];
  safetyScore: number; // 0-100
  advisoryLevel: AdvisoryLevel;
  advisoryLabel: AdvisoryLabel;
  topRisks: string[];
  crimeIndex: number; // 0-100, higher = more crime
  healthRisk: number; // 0-100, higher = more risk
  politicalStability: number; // 0-100, higher = more stable
  vaccinations: Array<{ name: string; required: boolean }>;
  tapWaterSafe: boolean;
  commonHealthRisks: string[];
  visaRequirements: {
    notRequired: boolean;
    onArrival: boolean;
    required: boolean;
    stayDays?: number;
    processingDays?: number;
    applicationFeeUsd?: number;
    applyOnlineUrl?: string;
    checklist: string[];
  };
}

export const SAFETY_DATA: SafetyData[] = [
  {
    country: 'Japan',
    destinations: ['Tokyo', 'Kyoto', 'Osaka'],
    safetyScore: 95,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Natural disasters (earthquakes, typhoons) — know evacuation routes'],
    crimeIndex: 14,
    healthRisk: 12,
    politicalStability: 92,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Japanese encephalitis (rural/long stay)', required: false },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal flu', 'Pollen allergies (spring)'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Return ticket'],
    },
  },
  {
    country: 'Thailand',
    destinations: ['Bangkok', 'Chiang Mai'],
    safetyScore: 72,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: [
      'Road accidents — tuk-tuks and motorbikes',
      'Scams (gem stores, jet ski damage)',
      'Tap water not safe — bottled only',
    ],
    crimeIndex: 42,
    healthRisk: 48,
    politicalStability: 65,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Dengue fever', 'Air pollution (Bangkok)'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 30,
      processingDays: 0,
      checklist: ['Valid passport', 'Return ticket', 'Proof of accommodation'],
    },
  },
  {
    country: 'Spain',
    destinations: ['Barcelona'],
    safetyScore: 78,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpocketing on Las Ramblas and Metro', 'Street scams (petitions, bracelets)'],
    crimeIndex: 38,
    healthRisk: 18,
    politicalStability: 78,
    vaccinations: [{ name: 'Routine (MMR, Tdap)', required: true }],
    tapWaterSafe: true,
    commonHealthRisks: ['Sun exposure', 'Dehydration in summer'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Schengen 90/180 rule applies'],
    },
  },
  {
    country: 'Italy',
    destinations: ['Rome', 'Florence', 'Amalfi Coast'],
    safetyScore: 76,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: [
      'Pickpocketing at tourist sites',
      'Restaurant scams near major monuments',
      'Traffic in Naples/Rome',
    ],
    crimeIndex: 40,
    healthRisk: 20,
    politicalStability: 72,
    vaccinations: [{ name: 'Routine (MMR, Tdap)', required: true }],
    tapWaterSafe: true,
    commonHealthRisks: ['Sun exposure', 'Heat in summer'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Schengen 90/180 rule applies'],
    },
  },
  {
    country: 'France',
    destinations: ['Paris'],
    safetyScore: 74,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpocketing in Metro and tourist areas', 'Street scams (gold ring, petition)'],
    crimeIndex: 44,
    healthRisk: 18,
    politicalStability: 75,
    vaccinations: [{ name: 'Routine (MMR, Tdap)', required: true }],
    tapWaterSafe: true,
    commonHealthRisks: ['Air pollution (Paris)', 'Seasonal flu'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Schengen 90/180 rule applies'],
    },
  },
  {
    country: 'Indonesia',
    destinations: ['Bali'],
    safetyScore: 68,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: [
      'Motorbike accidents — wear a helmet',
      'Rip currents at beaches',
      'Scams (money changers, rental damage)',
    ],
    crimeIndex: 48,
    healthRisk: 55,
    politicalStability: 62,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
      { name: 'Rabies (if touching animals)', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Dengue fever', 'Bali belly'],
    visaRequirements: {
      notRequired: true,
      onArrival: true,
      required: false,
      stayDays: 30,
      processingDays: 0,
      applicationFeeUsd: 35,
      checklist: ['Valid passport (6 months)', 'Return ticket', 'VOA or e-VOA'],
    },
  },
  {
    country: 'Morocco',
    destinations: ['Marrakech'],
    safetyScore: 62,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: [
      'Aggressive touts and scam guides',
      'Unregulated taxis — agree price first',
      'Food/water safety in street stalls',
    ],
    crimeIndex: 52,
    healthRisk: 42,
    politicalStability: 58,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Sun exposure', 'Foodborne illness'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Return ticket'],
    },
  },
  {
    country: 'Portugal',
    destinations: ['Lisbon'],
    safetyScore: 84,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpockets on Tram 28', 'Overpriced restaurants in tourist squares'],
    crimeIndex: 28,
    healthRisk: 15,
    politicalStability: 85,
    vaccinations: [{ name: 'Routine (MMR, Tdap)', required: true }],
    tapWaterSafe: true,
    commonHealthRisks: ['Sun exposure', 'Hills — comfortable shoes'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Schengen 90/180 rule applies'],
    },
  },
  {
    country: 'Iceland',
    destinations: ['Reykjavik'],
    safetyScore: 94,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Weather — sudden storms, hypothermia', 'Unmarked geothermal areas — stay on paths'],
    crimeIndex: 12,
    healthRisk: 10,
    politicalStability: 96,
    vaccinations: [{ name: 'Routine (MMR, Tdap)', required: true }],
    tapWaterSafe: true,
    commonHealthRisks: ['Extreme weather', 'Dehydration in dry air'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Return ticket'],
    },
  },
  {
    country: 'South Africa',
    destinations: ['Cape Town'],
    safetyScore: 58,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: [
      'Street crime — avoid walking alone at night',
      'Carjackings — keep doors locked',
      'Uneven healthcare — have travel insurance',
    ],
    crimeIndex: 72,
    healthRisk: 45,
    politicalStability: 52,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['HIV/AIDS prevalence', 'Tuberculosis', 'Traveler\'s diarrhea'],
    visaRequirements: {
      notRequired: true,
      onArrival: false,
      required: false,
      stayDays: 90,
      processingDays: 0,
      checklist: ['Valid passport', 'Return ticket', 'Yellow fever if transiting risk areas'],
    },
  },
  // --- Additional destinations ---
  {
    country: 'South Korea',
    destinations: ['Seoul'],
    safetyScore: 92,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Geopolitical tensions (North Korea border)', 'Air quality (spring yellow dust)', 'Extreme temperatures (summer heat, winter cold)'],
    crimeIndex: 18,
    healthRisk: 15,
    politicalStability: 78,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal flu', 'Air pollution in spring'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'K-ETA registration (free)'] },
  },
  {
    country: 'Argentina',
    destinations: ['Buenos Aires'],
    safetyScore: 62,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Petty theft in tourist areas', 'ATM/credit card skimming', 'Currency scams (unofficial exchange)'],
    crimeIndex: 58,
    healthRisk: 25,
    politicalStability: 48,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Sun exposure', 'Traveler\'s diarrhea'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'Return/onward ticket'] },
  },
  {
    country: 'Turkey',
    destinations: ['Istanbul'],
    safetyScore: 65,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Pickpocketing in tourist areas', 'Taxi scams (rigged meters)', 'Political demonstrations'],
    crimeIndex: 42,
    healthRisk: 28,
    politicalStability: 45,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Stray animal bites'],
    visaRequirements: { notRequired: false, onArrival: true, required: false, stayDays: 90, processingDays: 0, applicationFeeUsd: 50, applyOnlineUrl: 'https://www.evisa.gov.tr', checklist: ['Valid passport', 'e-Visa or sticker visa', 'Return ticket'] },
  },
  {
    country: 'Australia',
    destinations: ['Sydney', 'Queenstown'],
    safetyScore: 90,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['UV radiation (wear sunscreen year-round)', 'Marine wildlife (jellyfish, rip currents)', 'Bushfire season (Oct-Mar)'],
    crimeIndex: 22,
    healthRisk: 10,
    politicalStability: 90,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Sunburn', 'Insect bites'],
    visaRequirements: { notRequired: false, onArrival: false, required: true, stayDays: 90, processingDays: 1, applicationFeeUsd: 20, applyOnlineUrl: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', checklist: ['Valid passport', 'ETA or eVisitor visa', 'Return ticket'] },
  },
  {
    country: 'Mexico',
    destinations: ['Mexico City', 'Oaxaca'],
    safetyScore: 58,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Petty theft/pickpocketing', 'Express kidnapping (rare in tourist areas)', 'Altitude sickness (Mexico City is 7,350ft)'],
    crimeIndex: 55,
    healthRisk: 35,
    politicalStability: 52,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Altitude sickness (CDMX)', 'Montezuma\'s revenge'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 180, processingDays: 0, checklist: ['Valid passport', 'Tourist card (given on arrival)', 'Return ticket'] },
  },
  {
    country: 'UAE',
    destinations: ['Dubai'],
    safetyScore: 93,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Extreme heat (40°C+ in summer)', 'Strict local laws (alcohol, dress code, PDA)', 'Traffic/road safety'],
    crimeIndex: 10,
    healthRisk: 12,
    politicalStability: 88,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Heat exhaustion', 'Dehydration'],
    visaRequirements: { notRequired: true, onArrival: true, required: false, stayDays: 30, processingDays: 0, checklist: ['Valid passport (6 months)', 'Visa on arrival stamp'] },
  },
  {
    country: 'Netherlands',
    destinations: ['Amsterdam'],
    safetyScore: 88,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Bicycle accidents (tourists walk in bike lanes)', 'Pickpocketing at Centraal Station', 'Tourist-targeted scams'],
    crimeIndex: 28,
    healthRisk: 10,
    politicalStability: 88,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal allergies', 'Cycling injuries'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'Schengen area rules apply'] },
  },
  {
    country: 'Colombia',
    destinations: ['Medellín', 'Cartagena'],
    safetyScore: 55,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Petty theft (phone snatching)', 'Scopolamine (drink spiking)', 'Certain neighborhoods after dark'],
    crimeIndex: 62,
    healthRisk: 30,
    politicalStability: 42,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Yellow fever (if visiting jungle regions)', required: false },
      { name: 'Hepatitis A', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Mosquito-borne illness (dengue)', 'Traveler\'s diarrhea', 'Altitude sickness (Medellín is 5,000ft)'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'Return/onward ticket', 'Proof of funds'] },
  },
  {
    country: 'Georgia',
    destinations: ['Tbilisi'],
    safetyScore: 78,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Aggressive drivers', 'South Ossetia/Abkhazia borders (avoid)', 'Stray dogs'],
    crimeIndex: 20,
    healthRisk: 22,
    politicalStability: 58,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Traveler\'s diarrhea', 'Sun exposure'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 365, processingDays: 0, checklist: ['Valid passport', 'US citizens can stay up to 1 year'] },
  },
  {
    country: 'Vietnam',
    destinations: ['Hoi An'],
    safetyScore: 72,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Motorbike traffic (chaotic crossings)', 'Petty theft on beaches', 'Flooding (Oct-Nov)'],
    crimeIndex: 30,
    healthRisk: 35,
    politicalStability: 62,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: false },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Dengue fever', 'Traveler\'s diarrhea', 'Heat exhaustion'],
    visaRequirements: { notRequired: false, onArrival: false, required: true, stayDays: 90, processingDays: 3, applicationFeeUsd: 25, applyOnlineUrl: 'https://evisa.xuatnhapcanh.gov.vn', checklist: ['Valid passport (6 months)', 'e-Visa', 'Return ticket'] },
  },
  {
    country: 'India',
    destinations: ['Jaipur'],
    safetyScore: 52,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Aggressive touts/scams', 'Traffic chaos', 'Foodborne illness'],
    crimeIndex: 48,
    healthRisk: 55,
    politicalStability: 55,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: true },
      { name: 'Typhoid', required: true },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Traveler\'s diarrhea (very common)', 'Dengue fever', 'Air pollution'],
    visaRequirements: { notRequired: false, onArrival: false, required: true, stayDays: 60, processingDays: 3, applicationFeeUsd: 25, applyOnlineUrl: 'https://indianvisaonline.gov.in', checklist: ['Valid passport (6 months)', 'e-Tourist visa', 'Recent photo', 'Return ticket'] },
  },
  {
    country: 'New Zealand',
    destinations: ['Queenstown'],
    safetyScore: 93,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Adventure sport injuries', 'Rapid weather changes in mountains', 'Sandflies (south island)'],
    crimeIndex: 15,
    healthRisk: 8,
    politicalStability: 95,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Sunburn (strong UV)', 'Hypothermia (alpine areas)'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, applicationFeeUsd: 12, applyOnlineUrl: 'https://nzeta.immigration.govt.nz', checklist: ['Valid passport', 'NZeTA (electronic travel authority)', 'IVL levy paid'] },
  },
  {
    country: 'Croatia',
    destinations: ['Dubrovnik'],
    safetyScore: 85,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Extreme summer crowds', 'Sea urchins on rocky beaches', 'Heat exhaustion in summer'],
    crimeIndex: 20,
    healthRisk: 12,
    politicalStability: 82,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Sunburn', 'Dehydration in summer'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'Schengen area rules apply (Croatia joined 2023)'] },
  },
  {
    country: 'Hungary',
    destinations: ['Budapest'],
    safetyScore: 80,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpocketing on public transport', 'Overcharging at restaurants/bars', 'Ruin bar scams'],
    crimeIndex: 32,
    healthRisk: 15,
    politicalStability: 72,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal allergies', 'Thermal bath infections (rare)'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 90, processingDays: 0, checklist: ['Valid passport', 'Schengen area rules apply'] },
  },
  {
    country: 'United Kingdom',
    destinations: ['London'],
    safetyScore: 85,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpocketing on the Tube', 'Cycling in traffic', 'Phone snatching on mopeds'],
    crimeIndex: 35,
    healthRisk: 10,
    politicalStability: 82,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal flu', 'Pollen allergies'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 180, processingDays: 0, checklist: ['Valid passport', 'No visa needed for up to 6 months'] },
  },
  {
    country: 'United States',
    destinations: ['New York'],
    safetyScore: 75,
    advisoryLevel: 1,
    advisoryLabel: 'Safe',
    topRisks: ['Pickpocketing in Times Square/subway', 'Traffic/pedestrian safety', 'Extreme weather (heat waves, nor\'easters)'],
    crimeIndex: 40,
    healthRisk: 10,
    politicalStability: 75,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
    ],
    tapWaterSafe: true,
    commonHealthRisks: ['Seasonal flu', 'Air quality alerts in summer'],
    visaRequirements: { notRequired: true, onArrival: false, required: false, stayDays: 0, processingDays: 0, checklist: ['Domestic travel — no visa needed'] },
  },
  {
    country: 'Cambodia',
    destinations: ['Siem Reap'],
    safetyScore: 60,
    advisoryLevel: 2,
    advisoryLabel: 'Exercise Caution',
    topRisks: ['Petty theft/bag snatching', 'Landmine areas (stay on marked paths)', 'Tuk-tuk/taxi scams'],
    crimeIndex: 45,
    healthRisk: 48,
    politicalStability: 48,
    vaccinations: [
      { name: 'Routine (MMR, Tdap)', required: true },
      { name: 'Hepatitis A', required: true },
      { name: 'Typhoid', required: false },
    ],
    tapWaterSafe: false,
    commonHealthRisks: ['Dengue fever', 'Traveler\'s diarrhea', 'Heat exhaustion'],
    visaRequirements: { notRequired: false, onArrival: true, required: false, stayDays: 30, processingDays: 0, applicationFeeUsd: 30, checklist: ['Valid passport (6 months)', 'Visa on arrival ($30)', 'Passport photo', 'Return ticket'] },
  },
];

/** Find safety data for a destination */
export function getSafetyForDestination(destination: string): SafetyData | null {
  return (
    SAFETY_DATA.find((data) =>
      data.destinations.some((d) => destination.toLowerCase().includes(d.toLowerCase()))
    ) ?? null
  );
}
