// =============================================================================
// ROAM — Medical Abroad Intelligence
// What to do when you're sick, hurt, or in trouble in a foreign country.
// =============================================================================

export interface MedicalGuide {
  country: string;
  emergencyNumber: string;
  ambulanceNumber: string;
  policeNumber: string;
  /** Can you call 911/112 and expect English? */
  englishEmergency: boolean;
  englishNote: string;
  /** Hospital quality and costs */
  hospitalQuality: 'excellent' | 'good' | 'mixed' | 'limited';
  hospitalNote: string;
  /** Estimated ER visit cost without insurance */
  erCostRange: string;
  /** Do pharmacies sell prescription meds OTC? */
  pharmacyOTC: boolean;
  pharmacyNote: string;
  /** Water safety */
  tapWaterSafe: boolean;
  waterNote: string;
  /** Travel insurance advice */
  insurancePriority: 'critical' | 'recommended' | 'nice-to-have';
  insuranceNote: string;
  /** Common health risks */
  healthRisks: string[];
  /** Where to go for help */
  whereToGo: { condition: string; go: string }[];
}

const MEDICAL_GUIDES: MedicalGuide[] = [
  {
    country: 'JP',
    emergencyNumber: '119',
    ambulanceNumber: '119',
    policeNumber: '110',
    englishEmergency: false,
    englishNote: 'Limited English on 119. Say "eigo" (English) and your location. Tokyo has English-speaking dispatchers but rural areas do not.',
    hospitalQuality: 'excellent',
    hospitalNote: 'World-class hospitals in Tokyo and Osaka. JMIP-certified hospitals have English-speaking staff. Look for hospitals with international departments.',
    erCostRange: '¥10,000-50,000 ($70-350)',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies are well-stocked but most medication requires a prescription. Ibuprofen and basic pain relief available OTC. Japanese cold medicine (Pabron) is excellent.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe everywhere in Japan.',
    insurancePriority: 'recommended',
    insuranceNote: 'Japanese healthcare is high quality and relatively affordable, but you must pay upfront. Insurance ensures repatriation if needed.',
    healthRisks: ['Heat exhaustion in summer (Jul-Sep)', 'Altitude sickness on Mt. Fuji', 'Food allergies — ask about allergens in Japanese: "arerugi arimasu ka"'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any clinic (kurinikku). No appointment needed at most.' },
      { condition: 'Emergency', go: 'Call 119 or go to nearest hospital ER (kyuukyuu).' },
      { condition: 'Pharmacy needs', go: 'Matsumoto Kiyoshi, Daikoku Drug, or any drugstore (kusuriya).' },
    ],
  },
  {
    country: 'FR',
    emergencyNumber: '112',
    ambulanceNumber: '15 (SAMU)',
    policeNumber: '17',
    englishEmergency: true,
    englishNote: '112 operators speak English. SAMU (15) may have limited English outside Paris.',
    hospitalQuality: 'excellent',
    hospitalNote: 'Public hospitals are excellent. EU citizens with EHIC get reduced rates. Others pay upfront and claim insurance.',
    erCostRange: '€50-300',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (look for the green cross) are excellent. Pharmacists can recommend treatments and some medications are cheaper than in the US. Prescription needed for most antibiotics.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe. "Eau du robinet" is fine to drink everywhere.',
    insurancePriority: 'recommended',
    insuranceNote: 'Healthcare is affordable but upfront payment required. Insurance covers repatriation flights which can cost €50,000+.',
    healthRisks: ['Pickpocket stress injuries (seriously, watch your bag on the Metro)', 'Dehydration in summer — drink water, not just wine'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any pharmacy (pharmacie) — green cross sign. They can diagnose and recommend.' },
      { condition: 'Emergency', go: 'Call 15 (SAMU) or go to Urgences at any hospital.' },
      { condition: 'Dental emergency', go: 'SOS Dentistes: 01 43 37 51 00 (Paris).' },
    ],
  },
  {
    country: 'TH',
    emergencyNumber: '1669',
    ambulanceNumber: '1669',
    policeNumber: '191',
    englishEmergency: false,
    englishNote: '1669 has limited English. In Bangkok, Bumrungrad and Bangkok Hospital have English-speaking emergency lines.',
    hospitalQuality: 'good',
    hospitalNote: 'Private hospitals in Bangkok are world-class (medical tourism hub). Public hospitals are cheaper but crowded. Private hospitals accept international insurance.',
    erCostRange: '฿2,000-15,000 ($60-430) at private hospitals',
    pharmacyOTC: true,
    pharmacyNote: 'Most medications available without prescription — antibiotics, pain relief, anti-diarrhea. Pharmacists speak some English in tourist areas.',
    tapWaterSafe: false,
    waterNote: 'Do NOT drink tap water. Bottled water everywhere, 7-Eleven has it for ฿7. Ice in restaurants is usually safe (made from filtered water).',
    insurancePriority: 'critical',
    insuranceNote: 'Private hospitals are affordable by Western standards but costs add up fast. Scooter accidents without IDP invalidate most insurance. Get comprehensive coverage.',
    healthRisks: ['Travelers diarrhea — common first 2-3 days', 'Dengue fever in rainy season (Jun-Oct)', 'Scooter accidents — #1 cause of tourist injury', 'Dehydration from heat + spicy food'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any pharmacy — they can prescribe most things directly.' },
      { condition: 'Emergency', go: 'Bumrungrad Hospital (Bangkok), Bangkok Hospital, or any private hospital. They have English-speaking staff.' },
      { condition: 'Scooter accident', go: 'Go directly to nearest hospital ER. Call your insurance immediately.' },
    ],
  },
  {
    country: 'ID',
    emergencyNumber: '118',
    ambulanceNumber: '118',
    policeNumber: '110',
    englishEmergency: false,
    englishNote: 'Very limited English on emergency lines. Have your hotel call for you. BIMC Hospital in Bali has an English hotline.',
    hospitalQuality: 'mixed',
    hospitalNote: 'BIMC Kuta and Siloam in Bali are international-standard. Outside major cities, facilities are basic. Serious injuries may require medevac to Singapore or Jakarta.',
    erCostRange: 'Rp 500,000-5,000,000 ($30-320) at private',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies (apotek) have most basics OTC. Quality varies. Guardian pharmacy chain is reliable.',
    tapWaterSafe: false,
    waterNote: 'Never drink tap water. Even in nice hotels, use bottled. Watch out for ice in local warungs.',
    insurancePriority: 'critical',
    insuranceNote: 'Medevac to Singapore costs $20,000-50,000+. Scooter accidents without IDP void insurance. Get comprehensive coverage with medevac included.',
    healthRisks: ['Bali belly — extremely common', 'Scooter accidents', 'Dengue fever', 'Rabies from stray dogs — avoid petting strays', 'Sunburn — equatorial sun is brutal'],
    whereToGo: [
      { condition: 'Minor illness', go: 'BIMC Medical Centre Kuta or Nusa Dua. 24/7 English-speaking.' },
      { condition: 'Emergency', go: 'BIMC Hospital or Siloam Hospital. Have your hotel arrange transport.' },
      { condition: 'Serious injury', go: 'SOS International — can arrange medevac to Singapore.' },
    ],
  },
  {
    country: 'US',
    emergencyNumber: '911',
    ambulanceNumber: '911',
    policeNumber: '911',
    englishEmergency: true,
    englishNote: '911 has multilingual support in major cities.',
    hospitalQuality: 'excellent',
    hospitalNote: 'World-class facilities. Extremely expensive without insurance. An ER visit averages $2,200.',
    erCostRange: '$1,500-5,000+',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (CVS, Walgreens) carry good OTC selection. Prescription needed for antibiotics and most medication.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe in virtually all cities.',
    insurancePriority: 'critical',
    insuranceNote: 'US healthcare is extremely expensive. A broken arm can cost $7,500. Comprehensive travel insurance is essential for international visitors.',
    healthRisks: ['Medical bill shock', 'Regional: heat in Southwest, altitude in Colorado/Utah'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Urgent Care clinic (CVS MinuteClinic, CityMD). Cheaper than ER.' },
      { condition: 'Emergency', go: 'Call 911 or go to nearest ER.' },
      { condition: 'Pharmacy needs', go: 'CVS, Walgreens, or Rite Aid.' },
    ],
  },
  {
    country: 'ES',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: '112 in Spain has English-speaking operators.',
    hospitalQuality: 'excellent',
    hospitalNote: 'Public hospitals are excellent. EU citizens with EHIC get free care. Others pay upfront.',
    erCostRange: '€100-500',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (farmacia, green cross) are excellent. Pharmacists can diagnose and recommend. Some antibiotics available without prescription.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe. Tastes better in some regions than others.',
    insurancePriority: 'recommended',
    insuranceNote: 'Affordable healthcare but upfront payment for non-EU visitors. Insurance covers repatriation.',
    healthRisks: ['Heat stroke in summer (40°C+ in Andalucía)', 'Sunburn', 'Pickpocket-related injuries in Barcelona'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any farmacia — green cross sign. Open late in tourist areas.' },
      { condition: 'Emergency', go: 'Call 112 or go to Urgencias at any hospital.' },
    ],
  },
  {
    country: 'IT',
    emergencyNumber: '112',
    ambulanceNumber: '118',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: '112 has English support. 118 (ambulance) may not.',
    hospitalQuality: 'good',
    hospitalNote: 'Public hospitals are good but can be crowded. Pronto Soccorso (ER) triages by severity — non-emergencies wait hours.',
    erCostRange: '€50-300',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (farmacia) are well-stocked. Pharmacists can recommend medications. Some antibiotics OTC.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe. Rome\'s nasoni (public fountains) are drinkable.',
    insurancePriority: 'recommended',
    insuranceNote: 'EU citizens with EHIC covered. Others pay upfront and claim.',
    healthRisks: ['Heat exhaustion in summer Rome/Florence', 'Food poisoning from sketchy tourist restaurants near landmarks'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any farmacia. Open at night in rotation (farmacia di turno).' },
      { condition: 'Emergency', go: 'Call 118 or go to Pronto Soccorso at any hospital.' },
    ],
  },
  {
    country: 'MA',
    emergencyNumber: '15',
    ambulanceNumber: '15',
    policeNumber: '19',
    englishEmergency: false,
    englishNote: 'French and Arabic only. Have your riad call for you.',
    hospitalQuality: 'mixed',
    hospitalNote: 'Private clinics in Marrakech (Clinique Internationale) are decent. Public hospitals are basic. Serious cases: medevac to Casablanca or Europe.',
    erCostRange: '200-2,000 MAD ($20-200)',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies sell many medications OTC including antibiotics. French-trained pharmacists. Quality is generally good.',
    tapWaterSafe: false,
    waterNote: 'Do not drink tap water. Bottled water everywhere. Avoid ice in local spots.',
    insurancePriority: 'critical',
    insuranceNote: 'Healthcare is cheap but quality is uneven. Insurance with medevac coverage to Europe is important.',
    healthRisks: ['Travelers diarrhea — very common', 'Heat exhaustion', 'Dehydration', 'Food poisoning from street food (eat at busy stalls only)'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any pharmacie (green crescent). They can diagnose basic conditions.' },
      { condition: 'Emergency', go: 'Clinique Internationale de Marrakech. Have your riad arrange transport.' },
    ],
  },
  {
    country: 'PT',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: '112 operators speak English.',
    hospitalQuality: 'good',
    hospitalNote: 'Public hospitals (SNS) are good. Hospital Santa Maria and São José in Lisbon. Private clinics faster.',
    erCostRange: '€50-200',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (farmácia) are well-regulated. Pharmacists can recommend and some medications available OTC.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe throughout Portugal.',
    insurancePriority: 'recommended',
    insuranceNote: 'EU citizens with EHIC get free care. Others should have travel insurance.',
    healthRisks: ['Cobblestone ankle sprains (seriously, wear good shoes)', 'Sunburn', 'Dehydration on hilly walks'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any farmácia. Night pharmacies (farmácia de serviço) available.' },
      { condition: 'Emergency', go: 'Call 112 or go to Urgências at the nearest hospital.' },
    ],
  },
  {
    country: 'KR',
    emergencyNumber: '119',
    ambulanceNumber: '119',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: '119 has English support in Seoul. 1339 is the English medical helpline (24/7).',
    hospitalQuality: 'excellent',
    hospitalNote: 'World-class hospitals. Samsung Medical Center and Severance Hospital in Seoul have international clinics with English-speaking staff.',
    erCostRange: '₩30,000-200,000 ($22-150)',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies are everywhere. Pharmacists speak limited English. Basic OTC available. Korea has strict prescription requirements.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe but many Koreans drink filtered/bottled by preference.',
    insurancePriority: 'recommended',
    insuranceNote: 'Healthcare is affordable and high quality. Insurance still recommended for peace of mind and repatriation.',
    healthRisks: ['Air pollution days (check AQI app)', 'Spicy food stomach issues for first-timers'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Call 1339 (English medical helpline). Nearby clinic or pharmacy.' },
      { condition: 'Emergency', go: 'Call 119. Samsung Medical Center or Severance Hospital in Seoul.' },
    ],
  },
  {
    country: 'HU',
    emergencyNumber: '112',
    ambulanceNumber: '104',
    policeNumber: '107',
    englishEmergency: true,
    englishNote: '112 has English support. 104 (ambulance) operators may have limited English.',
    hospitalQuality: 'good',
    hospitalNote: 'Public hospitals are adequate. Private clinics like FirstMed in Budapest have English-speaking staff and shorter waits.',
    erCostRange: '€50-200',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (gyógyszertár/patika) are well-stocked. Some OTC medications available. Night pharmacies exist.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe in Budapest. Thermal bath water is NOT for drinking.',
    insurancePriority: 'recommended',
    insuranceNote: 'EU citizens with EHIC covered. Others should have travel insurance.',
    healthRisks: ['Thermal bath dehydration', 'Pickpockets on trams 4/6', 'Overindulgence at ruin bars'],
    whereToGo: [
      { condition: 'Minor illness', go: 'FirstMed Budapest (English-speaking). Teréz krt. 41.' },
      { condition: 'Emergency', go: 'Call 104 or 112. Szent János Hospital or Honvéd Hospital.' },
    ],
  },
  {
    country: 'TR',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '155',
    englishEmergency: true,
    englishNote: '112 has English support in Istanbul.',
    hospitalQuality: 'good',
    hospitalNote: 'Private hospitals in Istanbul are excellent (medical tourism destination). Acibadem and Memorial hospitals have English-speaking staff.',
    erCostRange: '₺500-3,000 ($15-90) at private',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies (eczane) sell many medications OTC including antibiotics. Pharmacists are well-trained.',
    tapWaterSafe: false,
    waterNote: 'Tap water is technically treated but most locals and visitors drink bottled. Available everywhere for ₺5.',
    insurancePriority: 'recommended',
    insuranceNote: 'Healthcare is affordable. Insurance still recommended for repatriation and peace of mind.',
    healthRisks: ['Travelers diarrhea — common', 'Food poisoning from street vendors (eat at busy spots)', 'Stray animal bites'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any eczane (pharmacy). They can recommend and sell directly.' },
      { condition: 'Emergency', go: 'Acibadem Maslak Hospital or Memorial Şişli. English-speaking ER.' },
    ],
  },
  {
    country: 'MX',
    emergencyNumber: '911',
    ambulanceNumber: '911',
    policeNumber: '911',
    englishEmergency: false,
    englishNote: '911 has limited English support. In Mexico City, tourist police speak English.',
    hospitalQuality: 'good',
    hospitalNote: 'Private hospitals in CDMX (Hospital Ángeles, ABC) are excellent. Public hospitals (IMSS) are crowded but free for emergencies.',
    erCostRange: '$50-500 at private hospitals',
    pharmacyOTC: true,
    pharmacyNote: 'Farmacias Similares and Farmacias del Ahorro sell many medications OTC including antibiotics. Attached doctors cost ₱35 for a consultation.',
    tapWaterSafe: false,
    waterNote: 'Do not drink tap water. Bottled water (agua purificada) everywhere. Garrafones (big jugs) in hotels are safe.',
    insurancePriority: 'recommended',
    insuranceNote: 'Private healthcare is affordable and good quality. Insurance useful for repatriation.',
    healthRisks: ['Montezuma\'s revenge (travelers diarrhea)', 'Altitude sickness in CDMX (2,240m)', 'Dehydration', 'Sunburn at altitude'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Farmacias Similares — ₱35 doctor consultation attached. Open late.' },
      { condition: 'Emergency', go: 'Hospital Ángeles or Hospital ABC in CDMX. English-speaking staff.' },
    ],
  },
  {
    country: 'CO',
    emergencyNumber: '123',
    ambulanceNumber: '123',
    policeNumber: '123',
    englishEmergency: false,
    englishNote: 'Limited English on 123. Have your hotel call. Tourist police in Cartagena speak English.',
    hospitalQuality: 'good',
    hospitalNote: 'Private hospitals in Medellín and Bogotá are excellent (Pablo Tobón Uribe, Fundación Santa Fe). Medical tourism destination.',
    erCostRange: 'COP 100,000-500,000 ($25-125)',
    pharmacyOTC: true,
    pharmacyNote: 'Droguerías sell many medications OTC. Pharmacists can recommend. Very affordable.',
    tapWaterSafe: true,
    waterNote: 'Tap water in Medellín, Bogotá, and Cartagena is safe. Smaller towns: use bottled.',
    insurancePriority: 'recommended',
    insuranceNote: 'Healthcare is affordable and high quality. Insurance good for peace of mind.',
    healthRisks: ['Altitude sickness in Bogotá (2,640m)', 'Mosquito-borne diseases at low altitude', 'Sunburn at altitude'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any droguería. Doctor consultation attached at many locations.' },
      { condition: 'Emergency', go: 'Clínica El Rosario or Pablo Tobón Uribe (Medellín). Fundación Santa Fe (Bogotá).' },
    ],
  },
  {
    country: 'AU',
    emergencyNumber: '000',
    ambulanceNumber: '000',
    policeNumber: '000',
    englishEmergency: true,
    englishNote: 'English is the primary language on 000.',
    hospitalQuality: 'excellent',
    hospitalNote: 'World-class public hospitals. Long ER waits for non-emergencies. Medicare reciprocal agreements with some countries.',
    erCostRange: 'A$300-1,000+',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (Chemist Warehouse, Priceline) are well-stocked. Prescription required for most medications.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe everywhere in Australia.',
    insurancePriority: 'critical',
    insuranceNote: 'Australian healthcare is expensive. Ambulance costs A$400-1,000+ in most states. Comprehensive insurance essential.',
    healthRisks: ['Extreme sun — wear SPF 50+, Australia has the highest skin cancer rate globally', 'Marine stingers in northern beaches (Nov-May)', 'Dehydration in the outback'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Medical centre (walk-in clinic) or Chemist Warehouse pharmacy.' },
      { condition: 'Emergency', go: 'Call 000. Go to nearest hospital Emergency Department.' },
    ],
  },
  {
    country: 'NL',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: 'All 112 operators speak English fluently.',
    hospitalQuality: 'excellent',
    hospitalNote: 'Excellent healthcare system. Register with a huisarts (GP) for non-emergencies. OLVG and AMC in Amsterdam.',
    erCostRange: '€100-400',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (apotheek) require prescriptions for most things. Albert Heijn and Kruidvat have basic OTC medicines.',
    tapWaterSafe: true,
    waterNote: 'Tap water is excellent. Among the best quality in Europe.',
    insurancePriority: 'recommended',
    insuranceNote: 'EU citizens with EHIC covered. Others need travel insurance.',
    healthRisks: ['Cycling injuries — most common tourist injury in Amsterdam', 'Allergic reactions from cannabis edibles'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Huisartsenpost (after-hours GP). No appointment needed.' },
      { condition: 'Emergency', go: 'Call 112. OLVG or AMC in Amsterdam.' },
    ],
  },
  {
    country: 'AE',
    emergencyNumber: '999',
    ambulanceNumber: '998',
    policeNumber: '999',
    englishEmergency: true,
    englishNote: 'English is widely spoken by emergency services in Dubai.',
    hospitalQuality: 'excellent',
    hospitalNote: 'World-class private hospitals. Dubai Healthcare City has international clinics. DHA health card may be required.',
    erCostRange: 'AED 500-3,000 ($136-817)',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies are well-stocked but strict. Many common medications (like codeine) require prescriptions or are banned entirely.',
    tapWaterSafe: true,
    waterNote: 'Tap water is desalinated and safe. Most people prefer bottled.',
    insurancePriority: 'critical',
    insuranceNote: 'Healthcare is expensive. A simple ER visit can cost AED 2,000+. Comprehensive insurance essential.',
    healthRisks: ['Heat exhaustion (summer temperatures exceed 45°C)', 'Dehydration', 'Sunburn'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Aster Clinic or any DHCC clinic. Walk-in available.' },
      { condition: 'Emergency', go: 'Call 998. Rashid Hospital or any Dubai Health Authority hospital.' },
    ],
  },
  {
    country: 'GE',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '112',
    englishEmergency: false,
    englishNote: 'Limited English on 112. Younger Georgians in Tbilisi speak English well — ask for help.',
    hospitalQuality: 'mixed',
    hospitalNote: 'Evex and MediClub in Tbilisi are private and good quality. Public hospitals are basic.',
    erCostRange: 'GEL 50-300 ($18-110)',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies (aptiaki) sell almost everything OTC including antibiotics. Very affordable.',
    tapWaterSafe: true,
    waterNote: 'Tap water in Tbilisi is safe. Mountain spring water is excellent.',
    insurancePriority: 'recommended',
    insuranceNote: 'Healthcare is cheap but insurance provides peace of mind and repatriation coverage.',
    healthRisks: ['Aggressive drivers — be careful crossing streets', 'Overindulgence at supras (feasts)'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any aptiaki (pharmacy) — they can recommend and sell directly.' },
      { condition: 'Emergency', go: 'MediClub Georgia or Evex hospitals. English-speaking staff available.' },
    ],
  },
  {
    country: 'IN',
    emergencyNumber: '112',
    ambulanceNumber: '108',
    policeNumber: '100',
    englishEmergency: true,
    englishNote: '112 has English support in major cities.',
    hospitalQuality: 'mixed',
    hospitalNote: 'Private hospitals (Fortis, Max, Apollo) are excellent. Public hospitals are very crowded. Private is worth the cost.',
    erCostRange: '₹2,000-15,000 ($24-180) at private',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies sell almost everything OTC. Very affordable. Quality is generally reliable from chain pharmacies.',
    tapWaterSafe: false,
    waterNote: 'Never drink tap water. Bottled water everywhere. Avoid ice in local restaurants.',
    insurancePriority: 'critical',
    insuranceNote: 'Private hospitals are affordable but costs add up. Insurance critical for medevac if needed for rural areas.',
    healthRisks: ['Delhi belly — extremely common, bring Imodium', 'Air pollution in Delhi', 'Mosquito-borne diseases', 'Heat stroke in summer'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any pharmacy. Apollo Pharmacy chain is reliable.' },
      { condition: 'Emergency', go: 'Fortis, Max, or Apollo hospital. English-speaking staff.' },
    ],
  },
  {
    country: 'NZ',
    emergencyNumber: '111',
    ambulanceNumber: '111',
    policeNumber: '111',
    englishEmergency: true,
    englishNote: 'English is the primary language.',
    hospitalQuality: 'excellent',
    hospitalNote: 'ACC (Accident Compensation Corporation) covers all accident injuries for visitors — you pay nothing for accident-related treatment.',
    erCostRange: 'NZ$0 for accidents (ACC covers it), NZ$80-300 for illness',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies are well-regulated. Limited OTC. Unichem and Life Pharmacy are the main chains.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe and excellent throughout NZ.',
    insurancePriority: 'recommended',
    insuranceNote: 'ACC covers accidents free. Insurance needed for illness and repatriation only.',
    healthRisks: ['Extreme UV — NZ has thin ozone layer, burn in 15 min', 'Hypothermia on mountain hikes', 'Adventure sport injuries (bungee, skydiving)'],
    whereToGo: [
      { condition: 'Minor illness', go: 'After-hours medical centre. No GP appointment needed.' },
      { condition: 'Emergency', go: 'Call 111. Nearest hospital ED.' },
      { condition: 'Adventure injury', go: 'ACC covers you — go to any hospital, no payment needed.' },
    ],
  },
  {
    country: 'IS',
    emergencyNumber: '112',
    ambulanceNumber: '112',
    policeNumber: '112',
    englishEmergency: true,
    englishNote: 'All Icelanders speak excellent English.',
    hospitalQuality: 'excellent',
    hospitalNote: 'Landspítali in Reykjavik is the main hospital. Excellent care. Very expensive for non-residents.',
    erCostRange: 'ISK 15,000-50,000 ($110-365)',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (apótek) are well-stocked but expensive. Bring common medications from home.',
    tapWaterSafe: true,
    waterNote: 'Tap water is some of the best in the world. Do NOT buy bottled water — it\'s literally the same water.',
    insurancePriority: 'critical',
    insuranceNote: 'Everything in Iceland is expensive. A simple clinic visit can cost ISK 15,000. Insurance essential.',
    healthRisks: ['Hypothermia — weather changes rapidly', 'Hot spring burns — some are boiling, not all are safe to enter', 'Rogue waves at Reynisfjara black sand beach — people die here every year'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Læknavaktin (medical center in Reykjavik). Walk-in.' },
      { condition: 'Emergency', go: 'Call 112. Landspítali Hospital.' },
    ],
  },
  {
    country: 'HR',
    emergencyNumber: '112',
    ambulanceNumber: '194',
    policeNumber: '192',
    englishEmergency: true,
    englishNote: '112 operators speak English.',
    hospitalQuality: 'good',
    hospitalNote: 'General Hospital Dubrovnik handles most cases. EU citizens with EHIC covered.',
    erCostRange: '€50-200',
    pharmacyOTC: false,
    pharmacyNote: 'Pharmacies (ljekarna) are standard European quality.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe in Dubrovnik and across Croatia.',
    insurancePriority: 'recommended',
    insuranceNote: 'EU citizens with EHIC covered. Others need travel insurance.',
    healthRisks: ['Heat exhaustion on city wall walk (no shade)', 'Jellyfish stings in summer', 'Sea urchin foot punctures'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any ljekarna (pharmacy).' },
      { condition: 'Emergency', go: 'Call 112. General Hospital Dubrovnik.' },
    ],
  },
  {
    country: 'VN',
    emergencyNumber: '115',
    ambulanceNumber: '115',
    policeNumber: '113',
    englishEmergency: false,
    englishNote: 'No English on 115. Have your hotel call. FV Hospital in HCMC has English ER.',
    hospitalQuality: 'mixed',
    hospitalNote: 'International hospitals in HCMC and Hanoi are good. Da Nang and Hoi An have basic facilities. Serious cases: medevac to HCMC or Bangkok.',
    erCostRange: 'VND 500,000-5,000,000 ($20-200)',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies sell most things OTC. Quality varies. Stick to branded medications.',
    tapWaterSafe: false,
    waterNote: 'Never drink tap water. Bottled water everywhere for 5,000 VND.',
    insurancePriority: 'critical',
    insuranceNote: 'Healthcare outside major cities is basic. Medevac coverage essential.',
    healthRisks: ['Travelers diarrhea', 'Motorbike accidents', 'Dengue fever', 'Hand-foot-mouth disease'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any pharmacy (nhà thuốc). They can diagnose and sell.' },
      { condition: 'Emergency', go: 'Family Medical Practice (Hanoi/HCMC/Da Nang). English-speaking.' },
    ],
  },
  {
    country: 'GB',
    emergencyNumber: '999',
    ambulanceNumber: '999',
    policeNumber: '999',
    englishEmergency: true,
    englishNote: 'English is the primary language. 111 for non-emergency medical advice.',
    hospitalQuality: 'excellent',
    hospitalNote: 'NHS provides excellent care. A&E (ER) is free for emergencies. Long waits for non-emergencies.',
    erCostRange: 'Free for emergencies (NHS)',
    pharmacyOTC: false,
    pharmacyNote: 'Boots and Superdrug pharmacies are well-stocked. Pharmacists can prescribe some medications.',
    tapWaterSafe: true,
    waterNote: 'Tap water is safe throughout the UK.',
    insurancePriority: 'nice-to-have',
    insuranceNote: 'NHS A&E is free for everyone. Insurance useful for repatriation and private care for shorter waits.',
    healthRisks: ['Pub-related injuries (seriously)', 'Rain-soaked cobblestone slips'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Call 111 (NHS helpline). Walk-in centres available.' },
      { condition: 'Emergency', go: 'Call 999 or go to nearest A&E (Accident & Emergency).' },
      { condition: 'Pharmacy needs', go: 'Boots pharmacy — can prescribe certain medications directly.' },
    ],
  },
  {
    country: 'ZA',
    emergencyNumber: '10177',
    ambulanceNumber: '10177',
    policeNumber: '10111',
    englishEmergency: true,
    englishNote: 'English is widely spoken by emergency services.',
    hospitalQuality: 'mixed',
    hospitalNote: 'Private hospitals (Netcare, Life Healthcare) are excellent. Public hospitals are overcrowded. Always go private if you have insurance.',
    erCostRange: 'R2,000-10,000 ($110-550) at private',
    pharmacyOTC: false,
    pharmacyNote: 'Clicks and Dis-Chem pharmacies are well-stocked. Pharmacists can recommend medications.',
    tapWaterSafe: true,
    waterNote: 'Tap water in Cape Town is safe and excellent quality.',
    insurancePriority: 'critical',
    insuranceNote: 'Private hospital care is expensive. Public hospitals should be avoided if possible. Comprehensive insurance essential.',
    healthRisks: ['Crime-related injuries', 'Sun exposure', 'Mosquitoes in northern regions'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Dis-Chem or Clicks pharmacy. Walk-in clinic at Mediclinic.' },
      { condition: 'Emergency', go: 'Call 10177. Netcare or Life Healthcare hospital.' },
    ],
  },
  {
    country: 'AR',
    emergencyNumber: '107',
    ambulanceNumber: '107',
    policeNumber: '101',
    englishEmergency: false,
    englishNote: 'Limited English. Hospital Alemán and Hospital Británico in BA have English-speaking staff.',
    hospitalQuality: 'good',
    hospitalNote: 'Public hospitals are free (even for foreigners) but crowded. Private hospitals (Hospital Alemán, Hospital Británico) are excellent.',
    erCostRange: 'Free (public) / ARS 20,000-100,000 at private ($20-100)',
    pharmacyOTC: true,
    pharmacyNote: 'Pharmacies sell many medications OTC. Very affordable. Farmacity chain is reliable.',
    tapWaterSafe: true,
    waterNote: 'Tap water in Buenos Aires is safe.',
    insurancePriority: 'recommended',
    insuranceNote: 'Public hospitals are free but crowded. Insurance gets you into private hospitals.',
    healthRisks: ['Stomach issues from water quality changes', 'Sunburn at altitude in the north'],
    whereToGo: [
      { condition: 'Minor illness', go: 'Any farmacia. Farmacity chain has attached clinics.' },
      { condition: 'Emergency', go: 'Hospital Alemán or Hospital Británico in BA. English-speaking.' },
    ],
  },
];

// ---------------------------------------------------------------------------
// Lookup
// ---------------------------------------------------------------------------

export function getMedicalGuide(countryCode: string): MedicalGuide | null {
  return MEDICAL_GUIDES.find((g) => g.country === countryCode) ?? null;
}

export function getMedicalGuideByDestination(destination: string): MedicalGuide | null {
  const normalized = destination.toLowerCase();
  // Try to match by checking if the destination name contains a known city
  // that maps to a country code
  const CITY_TO_COUNTRY: Record<string, string> = {
    tokyo: 'JP', kyoto: 'JP', osaka: 'JP',
    paris: 'FR', lyon: 'FR', nice: 'FR',
    bali: 'ID', jakarta: 'ID',
    bangkok: 'TH', 'chiang mai': 'TH', phuket: 'TH',
    'new york': 'US', 'los angeles': 'US', miami: 'US', chicago: 'US',
    barcelona: 'ES', madrid: 'ES', seville: 'ES',
    rome: 'IT', florence: 'IT', milan: 'IT', venice: 'IT',
    london: 'GB', edinburgh: 'GB', manchester: 'GB',
    marrakech: 'MA', fez: 'MA', casablanca: 'MA',
    lisbon: 'PT', porto: 'PT', faro: 'PT',
    seoul: 'KR', busan: 'KR',
    budapest: 'HU',
    istanbul: 'TR', cappadocia: 'TR',
    'mexico city': 'MX', oaxaca: 'MX', cancun: 'MX',
    amsterdam: 'NL', rotterdam: 'NL',
    dubai: 'AE', 'abu dhabi': 'AE',
    'cape town': 'ZA', johannesburg: 'ZA',
    sydney: 'AU', melbourne: 'AU',
    'buenos aires': 'AR', mendoza: 'AR',
    tbilisi: 'GE', batumi: 'GE',
    'hoi an': 'VN', hanoi: 'VN', 'ho chi minh': 'VN',
    dubrovnik: 'HR', split: 'HR', zagreb: 'HR',
    cartagena: 'CO', medellin: 'CO', bogota: 'CO',
    jaipur: 'IN', delhi: 'IN', mumbai: 'IN', goa: 'IN',
    queenstown: 'NZ', auckland: 'NZ',
    reykjavik: 'IS',
  };

  for (const [city, code] of Object.entries(CITY_TO_COUNTRY)) {
    if (normalized.includes(city)) {
      return getMedicalGuide(code);
    }
  }

  return null;
}
